config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :projects
  resources :contacts, only:  [:new, :create]
  get 'welcome/index'
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < MailForm::Base
	attribute :name,     :validate => true
	attribute :email,    :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
    attribute :message,  :validate => true
    attribute :nickname, :captcha  => true

    def headers 
    	{
    	:subject => "Contact Form",
    	:to => "mark.billes@web.de",
    	:from => %("#{name}" <#{email}>)
        }
    end
end

app/models/post.rb
class Post < ApplicationRecord
	extend FriendlyId
	friendly_id :title, use: :slugged
end

app/models/project.rb
class Project < ApplicationRecord
	extend FriendlyId
	friendly_id :title, use: :slugged
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	def new
		@contact = Contact.new
	end

	def create
		@contact = Contact.new(params[:contact])
		@contact.request = request
		if @contact.deliver
			flash.now[:error] = nil
		else
			flash.now[:error] = 'Cannot send message'
			render :new
		end
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :find_post, only: [:show, :edit, :update, :destroy]
	def index
		@posts = Post.all.order("created_at desc").paginate(page: params[:page], per_page: 10)
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new post_params

		if @post.save
			redirect_to @post, notice: "Hello Mark, your article was successfuly saved!"
		else 
			render 'new', notice: "Unable to save!"
		end
	end

	def show 
	end

	def edit
	end

	def update
		if @post.update post_params
			redirect_to @post, notice: "your article was saved!"
		else
			render 'edit'
		end
	end

	def destroy
		@post.destroy
		redirect_to posts_path
	end


	
    private

	def post_params
		params.require(:post).permit(:title, :content, :slug)
	end

	def find_post
		@post = Post.friendly.find(params[:id])
	end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	before_action :find_project, only: [:show, :edit, :update, :destroy]
	def index
	@projects = Project.all.order("created_at desc")
    end

    def new
    	@project = Project.new
    end

    def create
    	@project = Project.new project_params

    	if @project.save
    		redirect_to @project, notice: "Nice Mark, Project was succsessfully saved"
    	else
    		render 'new'
    	end
    end

    def show
    end

    def edit
    end

    def update 
    	if @project.update project_params
    		redirect_to @project, notice: "Nice Mark, Project was succsessfully updated"
    	else
    		render 'edit'
    	end
    end

    def destroy
        @project.destroy
        redirect_to projects_path
    end

    private

    def find_project
    	@project = Project.friendly.find(params[:id])
    end

    def project_params
    	params.require(:project).permit(:title, :description, :link, :slug)

    end

end

    	

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		@posts = Post.all.limit(3).order("created_at desc")
		@projects = Project.all.limit(3).order("created_at desc")
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def markdown(content)
		renderer = Redcarpet::Render::HTML.new(hard_wrap: true, filter_html: true)
		options = {
			autolink: true,
			no_intra_emphasis: true,
			disable_indented_code_blocks: true,
			fenced_code_blocks: true,
			lax_html_blocks: true,
			strikethrough: true,
			superscript: true
		}
	Redcarpet::Markdown.new(renderer, options).render(content).html_safe
	end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contacts/create.html.erb
<h1 id="page_title">Contact me</h1>

<div class="skyinny_wrapper wrapper_padding">
   <h1>Thank you for your message!</h1>
   <p>I'll get back to you soon</p>
</div>

app/views/contacts/new.html.erb
<h1 id="page_title">Contact me</h1>

	<div class="skyinny_wrapper wrapper_padding">
	<%= form_for @contact do |f| %>
	<%= f.label :name %><br>
	<%= f.text_field :name, required: true %>

	<br>

	<%= f.label :email %><br>
	<%= f.email_field :email, required: true %>

	<br>

	<%= f.label :message %><br>
	<%= f.text_area :message, as: :text %>


    <div class="hidden">
      <%= f.label :nickname %><br>
	<%= f.text_field :nickname, hint: 'leave this field blank' %>
    </div>

    <%= f.submit 'Send Message', class: "button" %>

	<% end %>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

<link href="https://fonts.googleapis.com/css?family=Roboto+Slab" rel="stylesheet">

    <title>Mark Billes - Back End Ruby on Rails Developer</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <header id="main_navigation" class="clearfix">
  <%= link_to "Mark Billes", root_path, class: "name" %>
	<nav>
	    <%= link_to "Articles", posts_path %> 
      <%= link_to "Projects", projects_path %>
		  <a href="#">Contact</a>


	</nav>

  </header>
  
 
  
    
    <%= yield %>

  <footer id="main_footer">
  <p class="copyright">&copy2016 Mark Billes</p>  
  </body>
</html>

app/views/posts/_disqus.html.erb
<div id="disqus_thread"></div>
<script>



(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');
s.src = '//billes.disqus.com/embed.js';
s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
                                

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
<% if @post.errors.any? %>
<h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving:</h2>
<ul>
  <% @post.errors.full_messages.each do |msg| %>
  <li><%= msg %></li> 
  <% end %>
</ul>
<% end %>

<%= f.label :title %><br>
<%= f.text_field :title %>

<br>
<br>

<%= f.label :content, "Write your article here" %><br>
<%= f.text_area :content %>

<br>
<br>


<%= f.submit %>



<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<h1 id="page_title">My Blog</h1>

	<div id="posts_wrapper" class="skinny_wrapper">
	<% @posts.each do |post| %>
	   <div class="post">
	<p class="date"><%= post.created_at.strftime('%A. %B %d') %></p>
	<h2><a href="#"><%= link_to post.title, post %></a></h2>
	<hr>
	</div>

<% end %>
	
</div>

	<%= will_paginate @posts %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<div id="post_show_content" class="skinny_wrapper wrapper_padding">
	<header>
		<p class="date"><%= @post.created_at.strftime('%A, %B %d') %></p>
		<h1><%= @post.title %></h1>
		<hr>
	</header>

	<div id="content">
	<%= markdown @post.content %>
	</div>

<hr>

<%= render 'disqus' %>

</div>

<%= link_to "Edit", edit_post_path(@post) %>
	

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
<% if @project.errors.any? %>
<h2><%= pluralize(@project.errors.count, "error") %> prevented this project from saving:</h2>
<ul>
  <% @project.errors.full_messages.each do |msg| %>
  <li><%= msg %></li> 
  <% end %>
</ul>
<% end %>

<%= f.label :title %><br>
<%= f.text_field :title %>

<br>
<br>

<%= f.label :description %><br>
<%= f.text_area :description %>

<br>
<br>

<%= f.label :link %><br>
<%= f.text_field :link %>

<br>
<br>

<%= f.submit %>



<% end %>

app/views/projects/edit.html.erb
<div class="skinny_wrapper wrapper_padding">
<h1>Edit Project</h1>
<%= render 'form' %>
</div>

app/views/projects/index.html.erb
<h1 id="page_title">Stuff I've Built</h1>

	<div id="posts_wrapper" class="skinny_wrapper">
	<% @projects.each do |project| %>
	   <div class="post">
	<p class="date"><%= project.created_at.strftime('%A. %B %d') %></p>
	<h2><a href="#"><%= link_to project.title, project %></a></h2>
	<hr>
	</div>

<% end %>
	
</div>

app/views/projects/new.html.erb
<div class="skinny_wrapper wrapper_padding">
<h1>New Project</h1>
<%= render 'form' %>
</div>

app/views/projects/show.html.erb
<div id="post_show_content" class="skinny_wrapper wrapper_padding">
	<header>
		<p class="date"><%= @project.created_at.strftime('%A, %B %d') %></p>
		<h1><%= @project.title %></h1>
		<hr>
	</header>

	<div id="content">
	<%= markdown @project.description %>


    <div class="button_wrapper">
	  <a href="<%= @project.link %>" class="project_button" target="_blank">Visit <%= @project.title %></a>

	</div>
	  
	</div>

	<%= link_to "Edit", edit_project_path(@project) %>
	<%= link_to "Delete", project_path(@project), method: :delete, data: { confirm: "Are you sure?"} %>

<hr>
</div>

app/views/welcome/index.html.erb
<div class="wrapper wrapper_padding clearfix">
	<div class="col-1 about homepage_content">
	<h2>About</h2>
	<hr>
	<p> I am a back-end developer focusing on ruby on rails. I'm currently going to University in Berlin and will be graduating in 2017.</p>
	<p>Ive only recently discovered my passion for programing and i keep on learning every day to become a true Rubyist</p>

	
	
	</div>

	<div class="col-2 homepage_content">
	<h2>My Blog</h2>
	<hr>

	<% @posts.each do |post| %>
	<h3><a href="#"><%= link_to post.title, post %></a></h3>
	<p class="date"><%= post.created_at.strftime("%A, %b, %d") %></p>


	<% end %>
	
	</div>
	<div class="col-3 homepage_content">
	<h2>My Projects</h2>
	<hr>
	<% @projects.each do |project| %>
	<h3><a href="#"><%= link_to project.title, project %></a></h3>
	<p class="date"><%= project.created_at.strftime("%A, %b, %d") %></p>


	<% end %>

	</div>


	</div>